qtile: fix number of @screen_change hook arguments
Log warns me that

    TypeError: restart_on_randr() missing 1 required positional
    argument: 'ev'

Which looks like the function should have one argument less (i.e. one
argument in total) but the documentation says there are supposed to be
no arguments at all. Let's accept anything.